// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIzEz7wZbRpizYJlCli7JX9vix2aBbUS8',
    appId: '1:814665772009:web:6b4ee4886992f874d7f978',
    messagingSenderId: '814665772009',
    projectId: 'warehouse-receipt-a9ad9',
    authDomain: 'warehouse-receipt-a9ad9.firebaseapp.com',
    storageBucket: 'warehouse-receipt-a9ad9.firebasestorage.app',
    measurementId: 'G-1KFKE9HTG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UXdL0O8Kf-gj6Dbt7tkpEKBxiDoIWiw',
    appId: '1:814665772009:android:6c7c26d79955698fd7f978',
    messagingSenderId: '814665772009',
    projectId: 'warehouse-receipt-a9ad9',
    storageBucket: 'warehouse-receipt-a9ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrTKDR-JE4mBAyN--AMSxm59KA64VvwDU',
    appId: '1:814665772009:ios:001fe926fec2020bd7f978',
    messagingSenderId: '814665772009',
    projectId: 'warehouse-receipt-a9ad9',
    storageBucket: 'warehouse-receipt-a9ad9.firebasestorage.app',
    iosBundleId: 'com.example.warehouseReceipt',
  );
}
